### ISSUE TITLE
Rx/Tx pins pulses voltage

### ISSUE THREAD

**Issue by renatoa** [jmoore52/SkywalkerRoaster#1]
Hi,

5V or 3.3V at peak of Rx/Tx pulses?
Asking to know if I can connect directly to an ESP board, allowing 3.3V only signals.

Thank you !

**Comment by kfhwang** [comment]
> Hi,
> 
> 5V or 3.3V at peak of Rx/Tx pulses? Asking to know if I can connect directly to an ESP board, allowing 3.3V only signals.
> 
> Thank you !

Hi,
In order to convert 3.3V to 5V, I used a level shifter between ESP32 and Skywalker Roaster.
However, it cannot send any command to Skywalker, but can read temperature from Skywalker.
Any suggestion?
Thank you very much!

**Comment by Krullus** [comment]
I measured the voltage on the signal from the roaster, and it was around 5V (5.28V on a not very accurate oscilloscope). Additionally, in the controller unit, it looks like both TX and RX are pulled-up to 5V.

**Comment by kfhwang** [comment]
Thank you. I measured the level shifter hive volt output pin, it is 4.8V. Maybe not enough to signal the roaster.

**Comment by renatoa** [comment]
Forgot to specify in the initial post that I am using the Spy version, not the Command version.
So I am listen only, on both wires, thus no need to command any line.
For listening only I used resistor dividers, to reduce 5V to 3.3V, thus  a passive solution, no active level shifting.

**Comment by kfhwang** [comment]
In the Command version, if ESP32 can send command message to roaster correctly, it is useful because ESP32 has Wifi, we can use websocket to communicate with Artisan, and use Artisan to control the roaster.

**Comment by renatoa** [comment]
Forget this, the WiFi in ESP devices disturbs all the timings of the Skywalker communication.
And for Skywalker the timings of the packets ARE critical. 
This is the reason I am using Spy version, because the way how the command packets are sent now is not reliable, and I experience machine lockups, due to packet delays.
Planning to split the packets handling between the two cores of ESP32, to have no interference from the main loop code in the process of sending fake controller packets to the roaster.
Better use a BT dongle, as serial wireless, is much safe.

**Comment by kfhwang** [comment]
I have used Arduino Leonardo (use command version code) and Artisan to control and monitor the Skywalker roaster. I just confused why Arduino Leonardo can send control message (get from Artisan) to Skywalker but ESP32 cannot. Even using a level shifter to convert the OUTPUT pin from 3.6V to 5V.

**Comment by renatoa** [comment]
This is curious, because experiments shows that ... beware, for an Arduino!
- voltage increasing from 0V, input switches to 1 at 2.60V;
- voltage decreasing from 5V, input switches to 0 at 2.35V.

Seems that an output GPIO of processor powered at 3.3V should be able to control an Arduino input... 
Not sure about chinese chips used in SkyWalker though...

**Comment by kfhwang** [comment]
ESP32 can receive message correctly from both Artisan and Skywalker roaster. But send message from ESP32 to roaster is not work. I think maybe the frequency of  pulsePin  is different with Arduino.  7500, 3800, 1500, 650 and 750 were used in jmoore52's code:

void sendMessage() {
  //send Preamble
  pulsePin(txPin, 7500);
  delayMicroseconds(3800);

  //send Message
  for (int i = 0; i < controllerLength; i++) {
    // Serial.printf("Send %d\t", sendBuffer[i]);
    for (int j = 0; j < 8; j++) {
      if (bitRead(sendBuffer[i], j) == 1) {
        pulsePin(txPin, 1500);  //delay for a 1
      } else {
        pulsePin(txPin, 650);  //delay for a 0
      }
      delayMicroseconds(750);  //delay between bits
    }
  }

**Comment by renatoa** [comment]
pulsePin is a function written by josh, look some lines above, is not Arduino specific.

You can easily check the length timing, send an empty (zeroed) buffer, and print millis() before and after.
Should give you about 90ms 7500+3800+7*8*(650+750) = 89700 us.

**Comment by kfhwang** [comment]
Thank you very much. I figured out how to send message from esp32 to skywalker correctly. Let txPin by level-shifter to roaster and rxPin connect to esp32 directly.

**Comment by kfhwang** [comment]
Thank you very much. Finally, ESP32 can be used for Artisan to  control Skywalker roaster by using WebSocket. If use TC4 between Artisan and  ESP32, Tx pin's signal will be disturbed  by roaster's power. However, when use WebSocket, it's workable.  Furthermore, WiFi did not disturb the timings of the Skywalker communication under my test.  Please refer to the attached layout if there is someone else interesting:
![ESP32_Slywalker](https://github.com/jmoore52/SkywalkerRoaster/assets/3859455/4171942a-ef9e-4a35-aa9e-c160484f0a02)

**Comment by renatoa** [comment]
How do you detect that Skywalker communication is not affected by wifi?
It is stated in the ESP documentation that wifi apps have the highest priority above any other task, so timer based apps  should be handled in a special way, if wifi is used.
You feel it as unaffected because broken packets crc checks fails, and they are skipped. 
No alarm is raised if too many control packets are lost, but you can experience sudden roaster stop without any apparent reason. The current batch will be lost obviously.
I experienced lost packets even with no wifi, for this reason I wrote the whole using interrupts.

**Comment by kfhwang** [comment]
Sorry for my statement of WiFi didn't distribute communication. When open the Serial monitor Arduino IDE, it shows some garbled characters. Fortunately, the communication between ESP32 and Skywalker only need few bytes. So, I skipped the code itsbeentoolong(), it is workable for me. 
Would you please share your code by using interrupts? I wonder to learn about how to work more fine. Thank you very much!

**Comment by xunlink** [comment]
First of all, thanks to the author, I am also esp32, I am looking for ways to do it without connecting to the computer entity.

**Comment by renatoa** [comment]
Why this desperate need for wireless?
Are you operating Skywalker remotely ? May I remind that coffee roasting is not an unattended activity ?

Packet based wifi, without a transport protocol, to handle check sums and retries, it's very unreliable, with lot of drops.
I tell this as a retired automation engineer, whose job born and grown up together with the Internet.
I had industrial crane automation projects where the result of first attempts to remote control using wifi led was seconds of frozen equipment.
Skywalker would not allow this, if no control packet arrive in a second, it stops and you have a trashed batch.

I am using ESP stuff mainly for memory allowing me to do things not possible with an Arduino.
If no wires are a project specification, and short distance, serial over BT is much more reliable than wifi, i.e. inside a room.
If the project impose wifi communication and long distance, I use a second ESP for wifi only, to avoid free run of code of the main process.
Even the much claimed multitasking is a joke, it's actually a switch between cores every one millisecond, which is a mess if it happens in the middle of a skywalker protocol pulse.

**Comment by xunlink** [comment]
I am very happy to receive your reply. Using wifi does not require remote control,  and using USB to connect to a computer within a short distance must be the safest. I quite agree with this point. But  I think a wireless connection over a short distance might be a more minimalist approach。
I really appreciate your willingness to reply to me. In the future, if there is a chance, we also look forward to seeing the addition of wireless control.

**Comment by xunlink** [comment]
@kfhwang 朋友妳好,我想知道,有沒有可能告訴我esp32的代碼如何實現控制.我現在碰到了和妳壹樣的難題

**Comment by xunlink** [comment]
@kfhwang 朋友妳好,我想知道,有沒有可能分享這個esp32通過wifi控制的代碼.我現在碰到了和妳壹樣的難題,
好難過

**Comment by renatoa** [comment]
Regarding air temperature... forget anything you know from the other roasters! 
Here air has the least influence on roasting, and this influence is for cooling, nothing else, not even the chaff exhaust.
Actually, in this machine the air is the coolest element in the chain. 
First is the lamp, then the beans, then the drum, and last is the air.
IR heat transfer is a very special beast of heating... completely different than convection or contact.
First... IR radiation pass through transparent gases and even glass without ceasing any or very little energy.
Think how  the sun heat the planets... the cosmic space is cold, right? ;)
The air is heating from the planet surface radiation, not directly from the sun... the higher the altitude you climb in the mountains, the colder become the air... ;)
The sun energy is transferred only to the solid surfaces, depending on their darkness, for this reason the whole IR theory gravitates around the "black body" concept.
So the energy inside the drum is absorbed by beans, and by drum wall, because is gray.
If drum would be shiny, as a polished metal, even the drum would be cold !
The air is heathen mainly from the beans and the drum, and also from lamp metallic sheath.
For all the reasons above, in this machine the air temperature tell you NOTH-ING... just think that the temperature of air at exhaust is about 120 C degrees... will draw on graph as an almost straight line, very little variations, in the middle of the graph, i.e. somewhere in the drying area... have you ever seen this in other machines ?

**Comment by renatoa** [comment]
> @kfhwang 朋友妳好,我想知道,有沒有可能分享這個esp32通過wifi控制的代碼.我現在碰到了和妳壹樣的難題, 好難過

Translation: Hello friend, I would like to know if it is possible to tell me how to control the esp32 code. I am encountering the same problem as you now.

**Comment by kfhwang** [comment]
@xunlink https://github.com/kfhwang/SkywalkerWebsocket

**Comment by kfhwang** [comment]
Your are right. Although the Skywalker roaster is a simple functional machine. It is indeed enough for home use. There are many roaster not only provide bean temperature, but also drum temp, inlet temp, air temp. Please refer to: https://www.roestcoffee.com/roestblog/bean-inlet-profiles
Some professional coffee roaster suggest to observe inlet temperature. For example, Scott Rao wrote this in his book: Coffee Roasting: Best Practices. Therefore, if MAX6675 can be used in ESP32, i will try to add a thermocouple inside the tube behind the upper fan  of Skywalker. Just for fun.

**Comment by renatoa** [comment]
All the Rao roast theory does not apply to Skywalker, sorry. It's mainly for convection machines.
Even his famous continuous declining RoR mantra can be skipped, this machine is a "slow start fast finish" type, where it's ok to have almost flat RoR.
Believe me, heat transfer techniques are far more than Rao, he is only the visible face, the PR of roasting.

**Comment by xunlink** [comment]
Thank you very much

**Comment by xunlink** [comment]
I'm so happy.It's been a long time since I've been exposed to such enthusiasm.
I am now using arduino uno，The basic function is good, but there are still problems with the temperature reading: the temperature does not climb in real time during the coffee roasting process, and there is a delay, let me give you an example.It is an established fact that when the temperature in the boiler is 100 degrees Celsius, artisan only exhibits 80 degrees Celsius, and ROR in artisan, failed

**Comment by xunlink** [comment]
This may not be a real-time temperature? I don't know that this phenomenon only exists for me.

**Comment by renatoa** [comment]
Not sure what you mean with "established fact"...
You see 100 on control panel display, and 80 in Artisan?

You can monitor the messages flow and post here some of them, by copy paste.
This can be done via Help/Serial menu, then check the box to start logging.

**Comment by xunlink** [comment]
测试后，将此项目上传到arduino Uno，实际温度不准确，工匠软件没有实时更新温度，似乎每3秒更新一次温度

**Comment by renatoa** [comment]
3 seconds is the default Artisan sampling interval.
You can change to one second the sampling rate, Config/Sampling Interval... menu
A warning will appear, ignore.

But this not explain 20 degrees difference... 20 degrees is more than one minute rise.

**Comment by kfhwang** [comment]
Just for reference, in my experience, set the sampling rate to 1sec, Arduino may not follow up the speed. Therefore, BT will lose sometimes during the recording. In contrast, ESP32 is fine when set sampling rate to 1sec.

**Comment by xunlink** [comment]
In fact, the temperature indication on the original skywalker controller is inaccurate and accompanied by delays.

So.Please let me explain how to find the temperature anomaly.
First, my Skywalker roaster. Prior to the author's project, I added a temperature probe to the skywalker


Before I came across your project, I mainly used eap32 to connect to this extra thermometer I installed. artisan software connected to Bluetooth for temperature monitoring.
When I came across your project, I was very surprised and happy。
![5FC82E5B-8851-402D-9206-1B394C5D49B5](https://github.com/jmoore52/SkywalkerRoaster/assets/60987908/7b56542a-26c2-4106-b9ed-e0f70545bada)


I am very happy to come into contact with your project now. After a few days of testing, the controls were perfect, but I found that the temperature was not sensitive in artisan.

**Comment by kfhwang** [comment]
I think the thermometer probe you added is a little too higher, if you roast less than 300g of coffee bean it will get higher temperature. Related to the location of probe, please refer to this video: https://www.youtube.com/watch?v=GbwrXuKsiCE

**Comment by xunlink** [comment]
@kfhwang  This is at the same level as the original thermometer, which is inaccurate even in the process of baking beans. The original controller is not sensitive to temperature feedback. It is very similar to the effect of the current author's project.
Maybe it's because I have an extra thermometer, so I feel it, and I try to exchange their positions. The result of the test is still the same. I don't know if I am an example.

**Comment by renatoa** [comment]
The original thermometer is accurate, but the mistake is your expectation to see same values as you see in other roasters.
The hot air based roaster are measuring a mix of hot air and beans, where hot air is always 20-30C degrees higher than beans.
In this machine is the contrary, air is taking heat from beans and is never hotter than them.

Also, there is no sensor delay, the heater is the culprit, the lamp has so big inertia, almost as a gas machine.
The response to air changes are almost instant, under 15 seconds, just check and see yourself.
The response to heat changes is other story, you should learn the machine behavior and plan the change at least 30 seconds in advance, same routine as for a gas roaster.
For this reason, if the roast progress tell you to change something, always start with changing the air, to see a fast response, then change the heat, about 10-15 seconds later, to maintain the trend induced by air change.

Related to the location of probe... the original placement is there with a reason... to hide the sensor from direct lamp radiation, in the shadow of the trier. Lamp-trier-sensor, are all in a straight line. 
The readings of any sensor placed out of the shade will be faked.

**Comment by renatoa** [comment]
> Just for reference, in my experience, set the sampling rate to 1sec, Arduino may not follow up the speed. Therefore, BT will lose sometimes during the recording. In contrast, ESP32 is fine when set sampling rate to 1sec.

They both read the same, there is no reason that ESP would read messages at other rate than Arduino.
With both boards you get about 3-4 temperature packets per second, missing other 6-7 packets because they overlap with control messages. This is by design, can't be changed without interrupt driven logic.

**Comment by renatoa** [comment]
This discussion derailed from the initial thread scope, about pin voltages.
If you want to discuss more on other Skywalker subjects, in a location with better visibility, please join HRO forum, and we continue there.
Will close now the issue, however you can PM me if something important or urgent.

**Comment by xunlink** [comment]
What is HRO forum?How do I join..
I saw a link on the home page of the project, but it's not working at the moment.

**Comment by renatoa** [comment]
https://homeroasters.org/forum/viewthread.php?thread_id=6979
